services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vol:test
    environment:
      - PUID=${UID:-911} # or specify a UID
      - PGID=${GID:-911} # or specify a GID
      - VOLUME_PATHS="/data"
    volumes:
      - "./files:/files"
      - "./data:/data"
