services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vol:test
    environment:
      - PUID=${PUID:-1029}
      - PGID=${PGID:-1029}
      - VOLUME_PATHS="/data"
    volumes:
      - "./files:/files"
      - "./data:/data"
